# RoleBindings to allow argocd-application-controller to manage resources in each acct-mdh* namepsace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin
  namespace: acct-mdh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin
  namespace: acct-mdh-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin
  namespace: acct-mdh-servicemesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin
  namespace: acct-mdh-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin
  namespace: acct-hedgehog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

# Allow Argo CD to manage prometheus operator CRs for monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-monitoring
  namespace: acct-mdh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-monitoring
  namespace: acct-mdh-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-monitoring
  namespace: acct-mdh-servicemesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-monitoring
  namespace: acct-mdh-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-monitoring
  namespace: acct-hedgehog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: acct-mdh-argocd

# RBAC to allow argocd-server permissions to view some resources in other namespaces
# Role rules taken from: https://raw.githubusercontent.com/argoproj/argo-cd/v1.7.3/manifests/cluster-rbac/argocd-server-clusterrole.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server
  namespace: acct-mdh
rules:
  - apiGroups:
      - ""
      resources:
        - events
      verbs:
        - list
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - limitranges
      - persistentvolumeclaims
      - pods
      - replicationcontrollers
      - resourcequotas
      - secrets
      - serviceaccounts
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
      - authorization.openshift.io
    resources:
      - rolebindings
      - roles
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - prometheusrules
      - servicemonitors
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
      - appprojects
      - argocdexports
      - argocds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - jaegertracing.io
    resources:
      - jaegers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kiali.io
    resources:
      - kialis
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterlogforwarders
      - clusterloggings
      - collectors
      - elasticsearches
      - kibanas
      - logforwardings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - maistra.io
    resources:
      - servicemeshcontrolplanes
      - servicemeshextensions
      - servicemeshmemberrolls
      - servicemeshmembers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.kiali.io
    resources:
      - monitoringdashboards
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authentication.istio.io
      - authentication.maistra.io
      - config.istio.io
      - networking.istio.io
      - security.istio.io
      - rbac.istio.io
      - rbac.maistra.io
    resources:
      - ""
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server
  namespace: acct-mdh-servicemesh
rules:
  - apiGroups:
      - ""
      resources:
        - events
      verbs:
        - list
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - limitranges
      - persistentvolumeclaims
      - pods
      - replicationcontrollers
      - resourcequotas
      - secrets
      - serviceaccounts
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
      - authorization.openshift.io
    resources:
      - rolebindings
      - roles
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - prometheusrules
      - servicemonitors
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
      - appprojects
      - argocdexports
      - argocds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - jaegertracing.io
    resources:
      - jaegers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kiali.io
    resources:
      - kialis
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterlogforwarders
      - clusterloggings
      - collectors
      - elasticsearches
      - kibanas
      - logforwardings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - maistra.io
    resources:
      - servicemeshcontrolplanes
      - servicemeshextensions
      - servicemeshmemberrolls
      - servicemeshmembers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.kiali.io
    resources:
      - monitoringdashboards
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authentication.istio.io
      - authentication.maistra.io
      - config.istio.io
      - networking.istio.io
      - security.istio.io
      - rbac.istio.io
      - rbac.maistra.io
    resources:
      - ""
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server
  namespace: acct-mdh-grafana
rules:
  - apiGroups:
      - ""
      resources:
        - events
      verbs:
        - list
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - limitranges
      - persistentvolumeclaims
      - pods
      - replicationcontrollers
      - resourcequotas
      - secrets
      - serviceaccounts
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
      - authorization.openshift.io
    resources:
      - rolebindings
      - roles
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - prometheusrules
      - servicemonitors
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
      - appprojects
      - argocdexports
      - argocds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - jaegertracing.io
    resources:
      - jaegers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kiali.io
    resources:
      - kialis
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterlogforwarders
      - clusterloggings
      - collectors
      - elasticsearches
      - kibanas
      - logforwardings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - maistra.io
    resources:
      - servicemeshcontrolplanes
      - servicemeshextensions
      - servicemeshmemberrolls
      - servicemeshmembers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.kiali.io
    resources:
      - monitoringdashboards
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authentication.istio.io
      - authentication.maistra.io
      - config.istio.io
      - networking.istio.io
      - security.istio.io
      - rbac.istio.io
      - rbac.maistra.io
    resources:
      - ""
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server
  namespace: acct-hedgehog
rules:
  - apiGroups:
      - ""
      resources:
        - events
      verbs:
        - list
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - limitranges
      - persistentvolumeclaims
      - pods
      - replicationcontrollers
      - resourcequotas
      - secrets
      - serviceaccounts
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
      - authorization.openshift.io
    resources:
      - rolebindings
      - roles
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - prometheusrules
      - servicemonitors
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
      - appprojects
      - argocdexports
      - argocds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - jaegertracing.io
    resources:
      - jaegers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kiali.io
    resources:
      - kialis
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterlogforwarders
      - clusterloggings
      - collectors
      - elasticsearches
      - kibanas
      - logforwardings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - maistra.io
    resources:
      - servicemeshcontrolplanes
      - servicemeshextensions
      - servicemeshmemberrolls
      - servicemeshmembers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.kiali.io
    resources:
      - monitoringdashboards
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authentication.istio.io
      - authentication.maistra.io
      - config.istio.io
      - networking.istio.io
      - security.istio.io
      - rbac.istio.io
      - rbac.maistra.io
    resources:
      - ""
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-server
  namespace: acct-mdh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-server
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-server
  namespace: acct-mdh-servicemesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-server
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-server
  namespace: acct-mdh-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-server
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: acct-mdh-argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-server
  namespace: acct-hedgehog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-server
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: acct-mdh-argocd
